const INTERNAL_SERVER_ERROR_CODE = 500;
const SUCCESS_CODE = 200
const CREATED_CODE = 201
const CONFLICT_CODE = 409
const BAD_REQUEST_CODE = 400

module.exports = { INTERNAL_SERVER_ERROR_CODE, SUCCESS_CODE, CREATED_CODE, CONFLICT_CODE, BAD_REQUEST_CODE }